### ISSUE TITLE
error when using Blinka caused by gc.mem_free()

### ISSUE THREAD

**Issue by Jayguitar** [adafruit/Adafruit_CircuitPython_PortalBase#11]
Using Blinka to run NASA image of the day example on a pitft results in the following error:
` response = self.network.fetch(self.url, timeout=timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_portalbase/network.py", line 429, in fetch
    print("Free mem: ", gc.mem_free())  # pylint: disable=no-member
AttributeError: module 'gc' has no attribute 'mem_free'`

I think because gc.mem_free() is a circuitpython specific attribute and not present in Cpython gc module

**Comment by makermelissa** [comment]
Thanks!
