### ISSUE TITLE
Reboot loop on MemoryError?

### ISSUE THREAD

**Issue by jfurcean** [adafruit/Adafruit_CircuitPython_PortalBase#14]
I noticed I was getting an infinite loop when trying to pull data from a particular json source on the MatrixPortal that I wasn't getting on the MagTag. Is this expected behavior? Why isn't it just raising the `MemoryError`?

https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/4e8bb185646c663292b3e16afdd6a9a15492d197/adafruit_portalbase/network.py#L551-L554

Here is my test code which is just a modified version of the `examples/matrixportal_simpletest.py` from [Adafruit_CircuitPython_MatrixPortal](https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal )

```py
import time
import board
import terminalio
from adafruit_matrixportal.matrixportal import MatrixPortal

# Set up where we'll be fetching data from
DATA_SOURCE = "https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data"

# 63 is USA
LOCATION_NUM = 63

DATE_LOCATION = ["vaccination_data", LOCATION_NUM, 'Date']
NAME_LOCATION = ["vaccination_data", LOCATION_NUM, 'LongName']
CENSUS_LOACTION = ["vaccination_data", LOCATION_NUM, 'Census2019']
ADMINISTER_1_LOCATION = ["vaccination_data", LOCATION_NUM, 'Administered_Dose1']
ADMINISTER_2_LOCATION = ["vaccination_data", LOCATION_NUM, 'Administered_Dose2']

matrixportal = MatrixPortal(
    url=DATA_SOURCE,
    json_path=(DATE_LOCATION, NAME_LOCATION,
               CENSUS_LOACTION, ADMINISTER_1_LOCATION,
               ADMINISTER_2_LOCATION),
)


while True:
    try:
        value = matrixportal.fetch()
        print("Response is", value)
    except (ValueError, RuntimeError) as e:
        print("Some error occured, retrying! -", e)

    time.sleep(3 * 60)  # wait 3 minutes
```

**Comment by makermelissa** [comment]
This was originally taken from the PyPortal library, and I hadn't seen it ever come into play before. I think the purpose was if some long running code used too much memory once in a while, the whole thing restarted and would recover. I'll have to take a look to see if I can improve memory usage, but if it's constantly causing boot loops then it would make sense to not automatically restart. The whole Portal system has grown a lot since its initial implementation.

**Comment by jfurcean** [comment]
I assumed something like that was the case. The above code never completes and infinitely soft boots on:
```py
value = matrixportal.fetch()
```

**Comment by jfurcean** [comment]
This may be caused by the data from the source. I went back to my MagTag project and received the following error.

````Some error occured, trying again later - syntax error in JSON````

I will investigate this a little more, but I still think this might need to be looked at.

**Comment by jfurcean** [comment]
I updated to the latest version of everything and everything is working, so I am not sure why it failed the first time on the `MatrixPortal` and why it stopped working on `MagTag`.

**Comment by jfurcean** [comment]
MagTag is working with latest everything, but the MatrixPortal still isn't. I accidentally saved `code.py` to `lib/` and thought it was working.

**Comment by makermelissa** [comment]
I was able to reproduce this issue using your test code.
