### ISSUE TITLE
Memory allocation failed using adafruit_display_text.label

### ISSUE THREAD

**Issue by lubarb** [adafruit/Adafruit_CircuitPython_PortalBase#15]
On the Matrix Display & Matrix portal from Adabox 016 I get an error running the Custom Scrolling Quote Board Matrix Display example from [https://learn.adafruit.com/aio-quote-board-matrix-display].

With a feed set up with quotes:

"Gratitude is the art of seeing a gift in everything" -Unknown (Added on:2020-12-03)
"I see little of more importance to the future of our country & our civilization than full recognition of the place of the artist" -John F. Kennedy (Added on:2021-01-12)
"...save us from succumbing to the tragic temptation of becoming cynical" -Martin Luther King Jr. (Added on:2021-01-17)'

and using two colors, I get the error within a minute or two. The error occurs both when connected to MU and also after unplugging/replugging the display.

In PortalBase __init__.py if I replace

> from adafruit_display_text.label import Label

with

> from adafruit_display_text.bitmap_label import Label

the error no longer occurs.

Circuit Python 6.1.0
Libraries adafruit-circuitpython-bundle-6.x-mpy-20210225

**Comment by kmatch98** [comment]
Thanks for adding this as an issue!

**Comment by makermelissa** [comment]
I went ahead and used the same quotes as in the issue, made sure all libraries were up to date (using .py files so that they don't save on memory to try and force it to happen), and am using CircuitPython 6.2.0-beta.2. I let it run for about 10 minutes with no issues. Please try updating to the latest CircuitPython 6.2.0 and see if that resolves your issue.

**Comment by lubarb** [comment]
To test things in a hopefully reproducible manner, reset my environment to:

CircuitPython 6.2.0-beta.2 on 2021-02-11
Freshly installed libraries from adafruit-circuitpython-bundle-6.x-mpy-20210225
![image](https://user-images.githubusercontent.com/15658271/109883199-10b9c900-7c49-11eb-93f5-8da0c047f82b.png)
and code freshly copied from https://learn.adafruit.com/aio-quote-board-matrix-display/code-the-quote-board

With this, the example ran for 20 minutes or so without problem. 

I then changed the SCROLL_DELAY setting in line 30 from .02 to .01, which I previously had found to make the problem appear more quickly.

I then ran the following test:

- I unplugged the Matrix Portal display for 10-20 seconds each time for a freshly booted environment
- I then plugged it in to a power-only USB charger, so there wouldn't be any interaction with Mu or the OS

I ran the test five times, with the following results:
- Crash at about 25 seconds
- Crash at about 25 seconds
- Ran for 5 minutes, I then stopped it
- Ran for 5 minutes, I then stopped it
- Crash at 2 minutes 38 seconds

From plugging it in to displaying the first quote took about 15 seconds of time.

I should note that when I changed the portalbase init.py file I only ran the one test that went fine for 20 minutes, so it's possible that might also have similar intermittent problems.

**Comment by lubarb** [comment]
I ran the same test with the modified init.py file.

Out of 10 tries, 9 ran for 5+ minutes before I stopped the runs. One time the display crashed at about 16 seconds - I haven't any idea what that was about.

**Comment by makermelissa** [comment]
After running it a while, I finally produced the error:
```
Replacing text area with : "...save us from succumbing to the tragic temptation of becoming cynical" -Martin Luther King Jr.
Traceback (most recent call last):
  File "code.py", line 92, in <module>
  File "/lib/adafruit_portalbase/__init__.py", line 245, in set_text
  File "/lib/adafruit_display_text/label.py", line 103, in __init__
MemoryError: memory allocation failed, allocating 784 bytes

Code done running.
```

It appears to be some kind of memory leak either in the usage of the label or the label itself.

**Comment by makermelissa** [comment]
Ok, I think the issue was that it may have been recreating the label over and over again.

**Comment by makermelissa** [comment]
Ok, I think the issue was that it may have been recreating the label over and over again.

**Comment by lubarb** [comment]
On the discord channel there was a suggestion that it might be memory fragmentation. However adding a gc.collect() just before the matrixportal.set_text call didn't fix it for me.

Always reassuring to know someone else also gets the error!

**Comment by makermelissa** [comment]
I realized the reason it was recreating the label over and over is because you can't adjust max_glyphs with an existing label and changing to a longer string results in the max_glyphs error. So I'm trying to explicitly set an existing label to None before recreating it and so far, so good.

**Comment by kmatch98** [comment]
May not be relevant to this issue, but wanted to point out there was a recent addition to the displayio code to eliminate the requirement on max_size of the Group. I think it’s in the latest beta 6.2. 

See this PR https://github.com/adafruit/circuitpython/pull/4233

**Comment by makermelissa** [comment]
Actually yeah, that is relevant. But the max_glyphs requirement would need to be removed from display_text first and then this library could be changed to reuse the label.

**Comment by kmatch98** [comment]
Another option to consider is using `bitmap_label` In place of `label`  It tends to use less RAM and also ignores the `max_size` variable.

**Comment by makermelissa** [comment]
I may eventually do that. I want to make sure it has all of the features that are being used and perform more testing. For now, I changed the code to only recreate the label if the text is longer as creating the label uses up a lot of memory. This seems to help a lot and I have not seen the issue after that change.
