### ISSUE TITLE
JSON handling for non application/json content types

### ISSUE THREAD

**Issue by fivesixzero** [adafruit/Adafruit_CircuitPython_PortalBase#3]
Some useful REST endpoints don't return with a `content-type` of `application/json` while still returning valid JSON, preventing the use of the library's built-in JSON parsing/processing.

I ran into this while working with the freely available [US National Weather Service forecast API](https://www.weather.gov/documentation/services-web-api), which can only respond with GeoJSON (`application/geo+json`) or JSON LD (`application/ld+json`).

As a [workaround in my project](https://github.com/fivesixzero/magtag-experiments/blob/main/weather-tag/code.py) I've just called directly into the MagTag object's `network.fetch_data(url)` to get a response string to parse and wrangle but it'd be nice to do it in a more elegant way with these types of endpoints.

**Comment by makermelissa** [comment]
Transferred issue here because that's where the applicable code now resides.

**Comment by makermelissa** [comment]
I did a big refactor with #8 and there is now an `add_json_content_type()` function.
