### ISSUE TITLE
Code stops running when network fails to connect.

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_PortalBase#4]
I successfully connected to the network repeatedly, and then on a refresh, received two different errors on two different resets - one unknown network error and one authentication error. Each time, it failed to the error and the code stopped running, and it required a hard reset to begin running the code again.

Through discussion with @makermelissa, we both agree it should retry a network connection on a failure. She is currently working on a refactor, and this could be included.

**Comment by makermelissa** [comment]
Transferred issue here because that's where the applicable code now resides.

**Comment by makermelissa** [comment]
@Kattni, have you noticed this issue since the refactor? I haven't seen it myself.

**Comment by kattni** [comment]
@makermelissa I haven't had the opportunity to use any code where this might have happened. If you're confident it's resolved, feel free to close the issue.

**Comment by makermelissa** [comment]
Sounds good, we can always reopen.
