### ISSUE TITLE
PyPortal push_to_io doesn't recognize precision key parameter

### ISSUE THREAD

**Issue by asmagill** [adafruit/Adafruit_CircuitPython_PortalBase#47]
Running Adafruit CircuitPython 6.3.0 on 2021-06-01; Adafruit PyPortal with samd51j20 with libraries from adafruit-circuitpython-bundle-6.x-mpy-20210717.

When pushing data to an Adafruit IO feed, including the precision parameter with floating point data ala `pyportal.push_to_io(key, value, precision=x)` fails with an error. `pyportal.network.push_to_io(key, value, precision=x)` (which is what `pyportal.push_to_io` appears to be a wrapper for) works, however.

Is this intentional or an oversight?

**Comment by makermelissa** [comment]
Probably an oversight.
