### ISSUE TITLE
BMP not displaying properly using set_background()

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_PortalBase#56]
Guessing this is just something related to changes in CP.

Was using this BMP for testing:
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/MagTag_Weather/bmps/weather_bg.bmp

And then this:
```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit MagTag with ESP32S2
>>> from adafruit_magtag.magtag import MagTag
>>> magtag = MagTag()
>>> magtag.graphics.set_background("/bmps/weather_bg.bmp")
>>> magtag.display.refresh()
>>>
```
results in all dark display.

It seems to be MagTag library related. This example *does* work:
```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit MagTag with ESP32S2
>>> import board
>>> import displayio
>>> display = board.DISPLAY
>>> bitmap = displayio.OnDiskBitmap("/bmps/weather_bg.bmp")
>>> tile_grid = displayio.TileGrid(bitmap, pixel_shader=bitmap.pixel_shader)
>>> group = displayio.Group()
>>> group.append(tile_grid)
>>> display.show(group)
>>> display.refresh()
>>> 
```

**Comment by makermelissa** [comment]
Problem is this line: https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/main/adafruit_portalbase/graphics.py#L84

New OnDiskBitmap wants a filename and not the data.
