### ISSUE TITLE
Multiple wifi

### ISSUE THREAD

**Issue by djh1997** [adafruit/Adafruit_CircuitPython_PortalBase#63]
The secrets.py looks suspiciously like a wpa_supplicant.conf file but we can only put one wifi in there is there a way to put multiple as I would love my tag to work at home and office

**Comment by tekktrik** [comment]
It looks like it tries a few times on the provided ssid and password, unless I'm misunderstanding:

https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/a9bc7d7a0bffb820e63dcb586180af3dbdc17a7d/adafruit_portalbase/network.py#L330-L357

**Comment by makermelissa** [comment]
> It looks like it tries a few times on the provided ssid and password, unless I'm misunderstanding:
Yeah, it looks like a ConnectionError is now returned, so #64 fixes that.

**Comment by djh1997** [comment]
thanks you everyone who's looking at this the idea is so i don't have to reprogram the tag so it looks like a change to allow a retry with next SSID on this part would be what would be an ideal implementation

> It looks like it tries a few times on the provided ssid and password, unless I'm misunderstanding:
> 
> https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/a9bc7d7a0bffb820e63dcb586180af3dbdc17a7d/adafruit_portalbase/network.py#L330-L357
