### ISSUE TITLE
Dealing with HTTP 500 Errors

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_PortalBase#81]
As stated in https://forums.adafruit.com/viewtopic.php?f=60&t=192584

The user was running into a 500 server error. It seems to be dying inside of network.py. I'm wondering if there's a better way to handle this or is it an error that we should leave as it is so the user can try/catch it?

**Comment by tekktrik** [comment]
I think it makes to have user code handle non-200 responses, since the remedy could be different depending on the use case.  But maybe passing along the response in the error would be helpful in that case?
